# AKS Desktop - Kubernetes Service for nginx
# Generated on 2025-10-14T14:28:52.294Z
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: new-aks-project-2345
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: nginx-project
    kubernetes.azure.com/generator: aks-desktop
    app: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: nginx
